import Header from "@/components/Header";
import Footer from "@/components/Footer";

const PrivacyPolicy = () => {
  return (
    <div className="bg-black text-white min-h-screen">
      <Header />
      <main className="container mx-auto px-6 py-24 max-w-4xl">
        <h1 className="text-4xl font-bold uppercase tracking-widest mb-2">Privacy Policy</h1>
        <p className="text-gray-400 text-sm mb-1">Effective date: 02/01/2022</p>
        <p className="text-gray-400 text-sm mb-12">Updated: 4/3/2024</p>

        <section className="space-y-12 text-gray-300 text-sm leading-relaxed">

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Introduction</h2>
            <p>
              Welcome to Gamr Inc. Gamr Inc. ("us", "we", or "our") operates https://gamr.africa and Gamr mobile application (hereinafter referred to as "Service"). Our Privacy Policy governs your visit to https://gamr.africa and Gamr mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Service. We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. Our Terms and Conditions ("Terms") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("agreement").
            </p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Definitions</h2>
            <ul className="space-y-4">
              <li><span className="text-white font-semibold">SERVICE</span> means the https://gamr.africa website and Gamr mobile application operated by Gamr Inc.</li>
              <li><span className="text-white font-semibold">PERSONAL DATA</span> means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
              <li><span className="text-white font-semibold">USAGE DATA</span> is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><span className="text-white font-semibold">COOKIES</span> are small files stored on your device (computer or mobile device).</li>
              <li><span className="text-white font-semibold">DATA CONTROLLER</span> means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</li>
              <li><span className="text-white font-semibold">DATA PROCESSORS (OR SERVICE PROVIDERS)</span> means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
              <li><span className="text-white font-semibold">DATA SUBJECT</span> is any living individual who is the subject of Personal Data.</li>
              <li><span className="text-white font-semibold">THE USER</span> is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Information Collection and Use</h2>
            <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Types of Data Collected</h2>

            <h3 className="text-white font-semibold mb-2">Personal Data</h3>
            <p className="mb-3">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc list-inside space-y-1 mb-3 ml-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
            </ul>
            <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.</p>

            <h3 className="text-white font-semibold mt-6 mb-2">Usage Data</h3>
            <p className="mb-3">We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device ("Usage Data").</p>
            <p className="mb-3">This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>

            <h3 className="text-white font-semibold mt-6 mb-2">Location Data</h3>
            <p className="mb-3">We may use and store information about your location if you give us permission to do so ("Location Data"). We use this data to provide features of our Service, to improve and customize our Service.</p>
            <p>You can enable or disable location services when you use our Service at any time by way of your device settings.</p>

            <h3 className="text-white font-semibold mt-6 mb-2">Tracking Cookies Data</h3>
            <p className="mb-3">We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
            <p className="mb-3">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.</p>
            <p className="mb-3">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
            <p className="mb-2">Examples of Cookies we use:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li><span className="text-white">Session Cookies:</span> We use Session Cookies to operate our Service.</li>
              <li><span className="text-white">Preference Cookies:</span> We use Preference Cookies to remember your preferences and various settings.</li>
              <li><span className="text-white">Security Cookies:</span> We use Security Cookies for security purposes.</li>
              <li><span className="text-white">Advertising Cookies:</span> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Use of Data</h2>
            <p className="mb-3">Gamr Inc. uses the collected data for various purposes:</p>
            <ul className="list-disc list-inside space-y-1 ml-4">
              <li>to provide and maintain our Service;</li>
              <li>to notify you about changes to our Service;</li>
              <li>to allow you to participate in interactive features of our Service when you choose to do so;</li>
              <li>to provide customer support;</li>
              <li>to gather analysis or valuable information so that we can improve our Service;</li>
              <li>to monitor the usage of our Service;</li>
              <li>to detect, prevent and address technical issues;</li>
              <li>to fulfill any other purpose for which you provide it;</li>
              <li>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
              <li>to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
              <li>to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
              <li>in any other way we may describe when you provide the information;</li>
              <li>for any other purpose with your consent.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Retention of Data</h2>
            <p className="mb-3">We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Transfer of Data</h2>
            <p className="mb-3">Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
            <p className="mb-3">If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to the United States and process it there.</p>
            <p className="mb-3">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
            <p>Gamr Inc. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Disclosure of Data</h2>
            <p className="mb-3">We may disclose personal information that we collect, or you provide:</p>
            <h3 className="text-white font-semibold mb-2">Disclosure for Law Enforcement</h3>
            <p className="mb-3">Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
            <h3 className="text-white font-semibold mb-2">Business Transaction</h3>
            <p className="mb-3">If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>
            <h3 className="text-white font-semibold mb-2">Other cases</h3>
            <p>We may disclose your information also to our subsidiaries and affiliates.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Security of Data</h2>
            <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Your Data Protection Rights Under GDPR</h2>
            <p className="mb-3">If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.</p>
            <p className="mb-3">We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
            <p className="mb-3">If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at <a href="mailto:legal@gamr.africa" className="text-white hover:underline">legal@gamr.africa</a>.</p>
            <p className="mb-3">In certain circumstances, you have the following data protection rights:</p>
            <ul className="list-disc list-inside space-y-1 ml-4 mb-3">
              <li>the right to access, update or to delete the information we have on you;</li>
              <li>the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</li>
              <li>the right to object. You have the right to object to our processing of your Personal Data;</li>
              <li>the right of restriction. You have the right to request that we restrict the processing of your personal information;</li>
              <li>the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;</li>
              <li>the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information.</li>
            </ul>
            <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Service without some necessary data.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Your Data Protection Rights under CalOPPA</h2>
            <p className="mb-3">CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. According to CalOPPA we agree to the following:</p>
            <ul className="list-disc list-inside space-y-1 ml-4 mb-3">
              <li>users can visit our site anonymously;</li>
              <li>our Privacy Policy link includes the word "Privacy", and can easily be found on the page specified above on the home page of our website;</li>
              <li>users will be notified of any privacy policy changes on our Privacy Policy Page;</li>
              <li>users are able to change their personal information by emailing us at <a href="mailto:legal@gamr.africa" className="text-white hover:underline">legal@gamr.africa</a>.</li>
            </ul>
            <h3 className="text-white font-semibold mb-2">Our Policy on "Do Not Track" Signals</h3>
            <p className="mb-3">We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
            <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Service Providers</h2>
            <p className="mb-3">We may employ third party companies and individuals to facilitate our Service ("Service Providers"), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
            <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Analytics</h2>
            <p className="mb-3">We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

            <h3 className="text-white font-semibold mb-2">Google Analytics</h3>
            <p className="mb-3">Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
            <p className="mb-3">For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://policies.google.com/privacy?hl=en</a></p>
            <p className="mb-6">We also encourage you to review Google's policy for safeguarding your data: <a href="https://support.google.com/analytics/answer/6004245" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://support.google.com/analytics/answer/6004245</a></p>

            <h3 className="text-white font-semibold mb-2">Firebase</h3>
            <p className="mb-3">Firebase is an analytics service provided by Google Inc.</p>
            <p className="mb-6">You may opt-out of certain Firebase features through your mobile device settings, such as your device advertising settings or by following the instructions provided by Google in their Privacy Policy: <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://policies.google.com/privacy?hl=en</a></p>

            <h3 className="text-white font-semibold mb-2">GitHub</h3>
            <p className="mb-3">GitHub is provided by GitHub, Inc. GitHub is a development platform to host and review code, manage projects, and build software.</p>
            <p className="mb-6">For more information on what data GitHub collects for what purpose and how the protection of the data is ensured, please visit GitHub Privacy Policy page: <a href="https://help.github.com/en/articles/github-privacy-statement" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://help.github.com/en/articles/github-privacy-statement</a></p>

            <h3 className="text-white font-semibold mb-2">AppsFlyer</h3>
            <p className="mb-3">AppsFlyer receives the following anonymised or pseudonymised data from Gamr:</p>
            <ul className="list-disc list-inside space-y-1 ml-4 mb-3">
              <li><span className="text-white">Registration Event:</span> A random identifier (instead of email) and User role (e.g., Player, Organizer).</li>
              <li><span className="text-white">Login Event:</span> A random identifier (instead of email).</li>
              <li><span className="text-white">Other Events:</span> Type of event, tournament name (anonymized), tournament slug, post type, post slug (anonymized), and post title (anonymized).</li>
            </ul>
            <p className="mb-3">We share this data with AppsFlyer to measure the effectiveness of our marketing campaigns, analyze user acquisition and in-app behavior, and optimize the Gamr app for a better user experience.</p>
            <p>AppsFlyer uses industry-standard security practices to protect your data. Learn more at <a href="https://www.appsflyer.com/legal/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://www.appsflyer.com/legal/privacy-policy/</a>. To opt out, contact us at <a href="mailto:legal@gamr.africa" className="text-white hover:underline">legal@gamr.africa</a>.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Payments</h2>
            <p className="mb-3">We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
            <p className="mb-3">We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council.</p>
            <p className="mb-3">The payment processors we work with are:</p>
            <ul className="space-y-2 ml-4">
              <li><span className="text-white font-semibold">Paystack</span> — <a href="https://paystack.com/terms" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://paystack.com/terms</a></li>
              <li><span className="text-white font-semibold">Flutterwave</span> — <a href="https://flutterwave.com/ng/terms" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://flutterwave.com/ng/terms</a></li>
              <li><span className="text-white font-semibold">PayPal</span> — <a href="https://www.paypal.com/us/legalhub/privacy-full" target="_blank" rel="noopener noreferrer" className="text-white hover:underline">https://www.paypal.com/us/legalhub/privacy-full</a></li>
            </ul>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Children's Privacy</h2>
            <p className="mb-3">Our Services are not intended for use by children under the age of 13 ("Children").</p>
            <p>We do not knowingly collect personally identifiable information from Children under 13. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Changes to This Privacy Policy</h2>
            <p className="mb-3">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
            <p className="mb-3">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update "effective date" at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          </div>

          <div>
            <h2 className="text-white text-lg font-bold uppercase tracking-wider mb-4">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, please contact us by email: <a href="mailto:legal@gamr.africa" className="text-white hover:underline">legal@gamr.africa</a></p>
          </div>

        </section>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
